### ISSUE TITLE
Weighted averages to improve prediction

### ISSUE THREAD

**Issue by brownbat** [eshapard/experimentalCardEaseFactor#12]
I know you don't work on this here anymore, but this might help your personal flash card project too. 

When I stumbled on your blog post about the ideal flash card app, it was like you were reading my mind. People shouldn't have to fiddle with scheduling, this is just curve fitting.

I really like the use of log() to make the feedback more pronounced.

One issue with your algorithm you might still run into is that cards that have a bad early streak will be really slow to update. Even if you have a long successful streak later, you could still get stuck in a version of "ease hell" until you have a really long streak of successes. (I haven't really studied the code, you might deal with this somehow...)

You can fix that if you calculate a running average of success, biasing the pass/fail rate more towards the later attempts.

So, say, in the Anki paradigm:
```
get all revlog rows matching cid as reviews
passfail = .5
weight = .2
for rev in reviews:
  if ease:
    passfail = (passfail * (1 - weight)) + (1 * (weight))
  else:
    passfail = passfail * (1-weight)
```
You'll want to fiddle with "weight" to get the right number, but higher will have more recency bias, somewhere between .1 and .3 is probably pretty close.

I know you're not actively developing for Anki anymore, but something like this might help your side project too.

You can close this issue, was just an idea. Best of luck with your own program!

**Comment by eshapard** [comment]
Thanks for the input... your idea looks similar to calculating an 
exponential moving average for the card's success rate. That's a good 
idea, as it keeps recent reviews relevant rather than being overwhelmed 
by a long history. It's a good idea and if anyone is interested in 
pursuing it, your code sample gives them a starting point.

Excerpts from Thomas Brownback's message of May 25, 2020 2:08 pm:

**Comment by brownbat** [comment]
Here's a version without the typos. This doesn't crash, but I'm a bit stumped on to test it. I tried making a tmp deck with a couple cards. I reviewed ahead to put in a bunch of results. One card I alternated pass/fail, the other I rung up a ton of fails then a ton of successes. 

Needless to say this didn't work, and when I was trying to figure out why Google sent me back to your site to read about the perils of filtered decks. I feel like you've been down some of these roads before.

Anyway, if someone else out there wants to try this **completely untested and possibly highly dangerous** mod out, replace L13-24 with the following:

EDIT: There are a a few major bugs in this, do not use it.

```
# introduced for calculating a moving average of successes,
# to lower the influence of older reviews on the algorithm
movingAverageWeight = 0.2
useMovingAverage = True

def findSuccessRate(cardID):
    reviews = mw.col.db.scalar(("select count() from revlog where type = 1 "
                                "and cid = ?"), cardID)
    if not reviews or reviews < minRevs:
        return 0, 0, 0, 0
    if useMovingAverage:
        reviews = mw.col.db.list(("select ease from revlog where type = 1 and "
                                  "cid = ?"), cardID)
        if reviews[0]:
            correct = reviews[0]
            for review in reviews[1:]:
                if review > 0:
                    correct = (correct * (1 - movingAverageWeight)
                               + (1 * movingAverageWeight))
                else:
                    correct = correct * (1 - movingAverageWeight)
        else:
            correct = 0
    else:
        correct = mw.col.db.scalar(("select count() from revlog where "
                                    "type = 1 and cid = ? and ease > 1"),
                                   cardID)
        if not correct:
            correct = 0
    avgEase = mw.col.db.scalar("select avg(1000*ivl/lastIvl) from revlog where"
                               " type = 1 and cid = ? and lastIvl > 0 and ivl "
                               "> 0 group by cid", cardID)
    if not avgEase:
        return 0, 0, 0, 0
    factor = int(round(avgEase))
    successRate = float(correct)/float(reviews)
    return reviews, correct, factor, successRate
```

**Comment by eshapard** [comment]
I think one of the problems is that you seem to have used the variable 
name 'reviews' to hold a list of response values from the review history. But 
'reviews' is already used as a variable to hold the total number of 
reviews in the log (and that variable gets used later to calculate 
success rate).

You probably need to change the name of the moving average that you're 
calculating and then return that in place of successRate.


Excerpts from Thomas Brownback's message of May 26, 2020 9:28 am:

**Comment by brownbat** [comment]
Great catch, thanks. There are like five variables and for some reason I decided to collide with one. review_list should work fine.

```
# introduced for calculating a moving average of successes,
# to lower the influence of older reviews on the algorithm
movingAverageWeight = 0.2
useMovingAverage = True


def findSuccessRate(cardID):
    reviews = mw.col.db.scalar(("select count() from revlog where type = 1 "
                                "and cid = ?"), cardID)
    if not reviews or reviews < minRevs:
        return 0, 0, 0, 0
    if useMovingAverage:
        review_list = mw.col.db.list(("select ease from revlog where type = 1"
                                      "and cid = ?"), cardID)
        if review_list[0]:
            correct = review_list[0]
            for review in reviews[1:]:
                if review > 0:
                    correct = (correct * (1 - movingAverageWeight)
                               + (1 * movingAverageWeight))
                else:
                    correct = correct * (1 - movingAverageWeight)
        else:
            correct = 0
    else:
        correct = mw.col.db.scalar(("select count() from revlog where "
                                    "type = 1 and cid = ? and ease > 1"),
                                   cardID)
        if not correct:
            correct = 0
    avgEase = mw.col.db.scalar("select avg(1000*ivl/lastIvl) from revlog where"
                               " type = 1 and cid = ? and lastIvl > 0 and ivl "
                               "> 0 group by cid", cardID)
    if not avgEase:
        return 0, 0, 0, 0
    factor = int(round(avgEase))
    successRate = float(correct)/float(reviews)
    return reviews, correct, factor, successRate

```

> I think one of the problems is that you seem to have used the variable name 'reviews' to hold a list of response values from the review history. But 'reviews' is already used as a variable to hold the total number of reviews in the log (and that variable gets used later to calculate success rate). You probably need to change the name of the moving average that you're calculating and then return that in place of successRate.

**Comment by brownbat** [comment]
I also split one of the lines incorrectly while linting. Missing a space here.
```
    if useMovingAverage:
        review_list = mw.col.db.list(("select ease from revlog where type = 1"
                                      " and cid = ?"), cardID)  # added a space to the beginning of this line
```
Also didn't update this variable:
```
            for review in review_list[1:]: # changed to review_list from reviews
```
This is getting pretty finicky, I'll go ahead and close this and fork.

**Comment by brownbat** [comment]
I incorporated these changes in [my fork](https://github.com/brownbat/experimentalCardEaseFactor), and also fixed some bugs (2.1 changed the function ja-dark used, for one.) I would PR but I've changed the algorithm so much I don't think it would behave the way you expect anymore.

Would you be willing to let me keep working on it and submit it to ankiweb for others to use? What kind of license or attribution would you like for that?

**Comment by eshapard** [comment]
Sure, you can post yours on AnkiWeb. Let's consider this GPL.

Excerpts from Thomas Brownback's message of June 9, 2020 4:30 pm:

**Comment by aleksejrs** [comment]
brownbat, why did you mark it as requiring Anki 2.1.25?
