### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by VincentOostelbos** [eshapard/experimentalCardEaseFactor#13]
I just installed the addon Experimental Card Ease Factor and am trying it out for the first time. It seemed to work for a few cards, but then I got the following error message:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-08-09 01:31:19

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 464, in handler
  File "aqt\reviewer.py", line 327, in _onAnswerButton
  File "C:\Users\Vin\AppData\Roaming\Anki2\addons21\1672712021\YesOrNo.py", line 65, in AKR_answerCard
    __oldFunc(self, ease)
  File "aqt\reviewer.py", line 268, in _answerCard
  File "aqt\reviewer.py", line 118, in nextCard
  File "aqt\reviewer.py", line 211, in _showQuestion
  File "aqt\gui_hooks.py", line 1687, in __call__
  File "lib\site-packages\anki\hooks.py", line 583, in runHook
  File "C:\Users\Vin\AppData\Roaming\Anki2\addons21\1672712021\experimentalCardEaseFactor.py", line 147, in adjust_ease
    printable_review_list += str(review_list[-1])
IndexError: list index out of range
```

As you can see, I am not using the most recent version of Anki, as this currently conflicts with some addons that I rather like. If it's just that, please let me know.

I did change one thing in the settings, which was to set the target_ratio from 0.85 to 0.90. After reading [this blog](https://eshapard.github.io/anki/anki-new-interval-after-a-lapse.html) and [this one](https://eshapard.github.io/anki/anki-auto-adjust-new-interval-after-a-lapse.html), I decided to tentatively set my lapse percentage to 0.75, and it was after that that I got the error message on my next review—but it was one that I got right, so presumably that should not be related. I just thought I would mention it anyway, just to be sure.

**Comment by eshapard** [comment]
I'm pretty sure it doesn't work for Anki 2.1. I wrote it for Anki 2.0

I think someone made a version for 2.1, though... check the other 
comments. It might be there.

**Comment by VincentOostelbos** [comment]
Hmm... but I got it [from Ankiweb](https://ankiweb.net/shared/info/1672712021), where it said it was compatible only with Anki 2.1.x, and it did work for a little bit before I got the error. Perhaps the one I got was already the 2.1 version, and the error was for another version? Or is the one that is on there still the 2.0 version after all, even though it says "Only supports Anki 2.1.x."?

**Comment by VincentOostelbos** [comment]
As it happens, I got an update on it the next time I launched Anki, and after installing that and restarting the program, I have not had any more problems. I didn't think it was that, as I had already launched Anki after the error occured, and did not get any update notification, but I still should have checked manually. Sorry about that. Anyway, it seems to be solved, now.
