### ISSUE TITLE
How to make sure that experimentalCardEaseFactor is running correctly?

### ISSUE THREAD

**Issue by Cardosaum** [eshapard/experimentalCardEaseFactor#7]
I recently installed both **experimentalCardEaseFactor** and **yesorno**. 

**yesorno** it is not working the way it should (I changed the `debugMsg` variable to `True` and it runs the `if debugMsg` lines, but there are still 4 answer options: _Again_, _Hard_, _Good_ and _Easy_)

how can I make sure **experimentalCardEaseFactor** is running the way it should?

and, would it be better to create a new question just to solve the **yesorno** problem reported above?

if this information is useful:

**Anki**
- Version 2.0.52
- Qt 4.8.1 PyQt 4.9.1

**System**
- Operating system: Linux Lubuntu, LXDE 
- Version: Ubuntu 18.04 LTS

**Comment by eshapard** [comment]
I tested yesorno an 2.0.52 and it worked for me. My guess is you have another addon that's breaking it.

To test that the experimental addon is working, you could use the pop-up option to see what ease factor it calculates for a card. Then view the card in the browser or in the sql database and check to see if the ease factor was changed to that value.

**Comment by Cardosaum** [comment]
Yes, you guessed it. had an addon that was conflicting with yesorno.py - the [More Answer Buttons for New Cards](https://ankiweb.net/shared/info/153603893) addon.

I do not know how Anki was working properly on the previous installation with these two addons in the `addons` directory

I did some testing with the tip you gave and **experimentalCardEaseFactor** is working correctly

Many thanks for the help and for making (and sharing) these addons!
